@extends('admin.layouts.app')
@section('title', 'Paket Sewa')
@section('heading', 'Paket Sewa')
@section('subheading', 'Atur harga dan fasilitas paket yang tampil di katalog.')
@section('content')
<div class="mb-6 flex justify-end"><a href="{{ route('admin.packages.create') }}" class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-500">+ Tambah Paket</a></div>
<div class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-800 text-left text-sm">
<thead class="text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Paket</th><th class="px-6 py-4">Konsol</th><th class="px-6 py-4">Harga</th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Aksi</th></tr></thead>
<tbody class="divide-y divide-slate-800">@forelse($packages as $package)<tr class="hover:bg-slate-800/40"><td class="px-6 py-4"><p class="font-semibold text-white">{{ $package->name }}</p><p class="mt-1 max-w-md truncate text-xs text-slate-500">{{ $package->features }}</p></td><td class="px-6 py-4 text-slate-400">{{ $package->console->name }}</td><td class="px-6 py-4 font-semibold text-white">Rp{{ number_format($package->price, 0, ',', '.') }}</td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $package->is_published ? 'bg-emerald-500/10 text-emerald-400' : 'bg-slate-700 text-slate-400' }}">{{ $package->is_published ? 'Aktif' : 'Draf' }}</span></td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.packages.edit', $package) }}" class="rounded-lg bg-blue-500/10 px-3 py-2 text-xs font-semibold text-blue-300">Edit</a><form method="POST" action="{{ route('admin.packages.destroy', $package) }}" onsubmit="return confirm('Hapus paket ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-red-500/20 px-3 py-2 text-xs font-semibold text-red-400">Hapus</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-slate-500">Belum ada paket sewa.</td></tr>@endforelse</tbody>
</table></div>@if($packages->hasPages())<div class="border-t border-slate-800 px-6 py-4">{{ $packages->links() }}</div>@endif</div>
@endsection
